#!/bin/bash
#XDG_CONFIG_HOME/X11/xinitrc

[[ -d /etc/X11/xinit/xinitrc.d ]] && {
    for f in /etc/X11/xinit/xinitrc.d/*; do
        [[ -x "$f" ]] && source "$f"
    done
    unset f
}

[[ -d $XDG_CONFIG_HOME/X11/xinitrc.d ]] && {
    for f in "$XDG_CONFIG_HOME"/X11/xinitrc.d/*; do
        [[ -x "$f" ]] && source "$f"
    done
    unset f
}
